angular.module('app.services').factory("urlAPI", [
    function() {
        'use strict';
        var report = "/report/da";
        var push = "/push/push/";

        return {
            /*report device dashboard*/
            report_device_total: report + '/deviceTotalSales',
            report_device_daily: report + '/deviceDaily',
            report_device_newincrese: report + '/deviceNewIncrease',
            report_device_hotmodel: report + '/deviceHotModel',
            report_device_trend: report + '/deviceRecentTrend',
            report_device_hotregion: report + '/deviceHotRegion',
            report_device_topSales: report + '/deviceTopSales',
            report_device_operator: report + "/deviceOperator",
            report_device_language: report + "/deviceLanguage",
            report_device_android_version: report + "/deviceAndroidVersion",
            report_device_resolution: report + "/deviceResolution",
            /*device sales detail*/
            report_model_trend: report + "/deviceModelTrend",
            report_region_trend: report + "/deviceRegionTrend",
            report_detail_condition: report + '/condition',
            report_channel_rank: report + '/deviceChannelRank',
            report_model_rank: report + '/deviceModelRank',
            report_range_rank: report + '/deviceRegionRank',
            report_model_table: report + '/deviceModelDetail',
            report_region_table: report + '/deviceRegionDetail',
            /*APP Condition*/
            report_app_applist_condition:report+"/app/appList",
            report_app_detail_condition:report+"/app/appDetailCondition",
            /*APP overview*/
            report_app_over_basic:report+'/app/appBasic',
            report_app_over_new:report+'/app/appNewUserOV',
            report_app_over_active:report+'/app/appActiveUserOV',
            report_app_over_active_rate:report+'/app/appActiveRateOV',
            report_app_over_model_new:report+'/app/appModelNewUserOV',
            report_app_over_model_active:report+'/app/appModelActiveUserOV',
            report_app_over_model_rate:report+'/app/appModelActiveRateOV',
             /*APP Comparison*/
            report_app_compar_new_user:report+'/app/appComparisonNewUser',
            report_app_compar_active_user:report+'/app/appComparisonActiveUser',
            report_app_compar_rate_user:report+'/app/appComparisonActiveRateUser',
            report_app_compar_detail:report+'/app/appComparisonDetail',
             /*APP New User*/
            report_app_newuser_modelTrend:report+'/app/appNewUserModelTrend',
            report_app_newuser_channelTrend:report+'/app/appNewUserChannelTrend',
            report_app_newuser_channelRank:report+'/app/appNewUserChannelRank',
            report_app_newuser_modelRank:report+'/app/appNewUserModelRank',
            report_app_newuser_regionRank:report+'/app/appNewUserRegionRank',
            report_app_newuser_channelDetail:report+'/app/appNewUserChannelDetail',
            report_app_newuser_modelDetail:report+'/app/appNewUserModelDetail',
            /*APP Active User*/
            report_app_activeuser_modelTrend:report+'/app/appActiveUserModelTrend',
            report_app_activeuser_modelRate:report+'/app/appActiveRateModelTrend',
            report_app_activeuser_channelTrend:report+'/app/appActiveUserChannelTrend',
            report_app_activeuser_channelRate:report+'/app/appActiveRateChannelTrend',
            report_app_activeuser_channelRank:report+'/app/appActiveUserChannelRank',
            report_app_activeuser_modelRank:report+'/app/appActiveUserModelRank',
            report_app_activeuser_regionRank:report+'/app/appActiveUserRegionRank',
            report_app_activeuser_channelDetail:report+'/app/appActiveUserModelDetail',
            report_app_activeuser_modelDetail:report+'/app/appActiveUserChannelDetail',
            /*push 接口*/
            pushAllApp: push + "allapp",
            push_delPush: push + "deletePush",
            pushGetDevice: push + "devices",
            pushGetSegment: push + "appSegmentList",
            pushGetConfig: push + "getconfig",
            push_setConfig: push + "config",
            pushConfirm: push + "confirm",
            pushActive: push + "active",
            pushSetInMsg: push + "setInMessage",
            pushSaveInMsg: push + "saveInMessage",
            pushSetSchedule: push + "setSchedule",
            pushSaveSchedule: push + "saveSchedule",
            pushSetReceiver: push + "setReceiver",
            pushUploadIds: push + "uploadIds",
            push_saveReceiver: push + "saveReceiver",
            push_msgList: push + "messageListPage",
            push_duplicate: push + "duplicate",
            pushDelInMsg: push + "deleteInMessage",
            push_delNtfMsg: push + "deleteNtfMessage",
            push_inactive: push + "inactive",
            push_setNtfMsg: push + "setNtfMessage",
            push_uploadImg: push + "uploadNtfImg",
            push_uploadVideo: push + "uploadNtfVideo",
            push_uploadPostImg: push + "uploadNtfPostImg",
            push_clearMedia: push + "clearNtfMediaMessage",
            push_saveNtfMsg: push + "saveNtfMessage",
            push_overview: push + "reportoverview",
            push_arrive: push + "reportarrive",
            push_click: push + "reportclick",
            push_display: push + "reportdisplay",
            push_arriveTable: push + "tablearrive",
            push_clickTable: push + "tableclick",
            push_displayTable: push + "tabledisplay",
            push_step: push + "stepStatus",
            push_segment: push + "segmentListPage",
            push_segmentDelete: push + "deleteSegment",
            push_segmentDetail: push + "segmentDetail",
            push_segmentNew: push + "saveSegment",
            push_segmentUpdate: push + "updateSegment",
            push_segmentCondition: push + "segmentCondition",
            push_weeklyReport: push + "weeklyReport",
            push_weeklyHistory: push + "weeklyHistoryListPage",
            push_launcherList: push + "launcherPushList",
            push_launcherDelete: push + "deleteLauncherPush",
            push_launcherDuplicate: push + "duplicateLauncherPush",
            push_launcherActive: push + "launcherActivate",
            push_launcherDetail: push + "setLauncherPush",
            push_launcherEdit: push + "saveLauncherPush",
            push_launcherDevices: push + "launcherDevices",
            push_launcherTokens: push + "uploadTokens",
            /*campaign接口*/
            campaign_versionList: "/campaign/util/2003",
            campaign_appList: "/campaign/util/2002",
            campaign_detailList: "/campaign/util/2005",
            campaign_manage_list: "/campaign/place/5006",
            campaign_manage_detail: "/campaign/place/5002",
            campaign_manage_state: "/campaign/place/5003",
            campaign_manage_save: "/campaign/place/5005",
            campaign_manage_add: "/campaign/place/5004",
            campaign_manage_delete: "/campaign/place/5007",
            campaign_place_type: "/campaign/util/2012",
            campaign_place_list: "/campaign/place/5001",
            campaign_placement_list: "/campaign/advScheduler/40001",
            campaign_placement_detail: "/campaign/operate/7002",
            campaign_placement_state: "/campaign/advScheduler/40004",
            campaign_placement_priority: "/campaign/advScheduler/40002",
            campaign_show_list: "/campaign/type/4001",
            campaign_show_detail: "/campaign/type/4002",
            campaign_show_state: "/campaign/type/4003",
            campaign_show_new: "/campaign/type/4004",
            campaign_show_edit: "/campaign/type/4005",
            campaign_show_fields: "/campaign/util/2016",
            campaign_show_delete: "/campaign/type/4006",
            campaign_group_list: "/campaign/group/6001",
            campaign_group_detail: "/campaign/group/6002",
            campaign_group_state: "/campaign/group/6003",
            campaign_group_new: "/campaign/group/6004",
            campaign_group_edit: "/campaign/group/6005",
            campaign_group_delete: "/campaign/group/6007",
            campaign_group_place: "/campaign/util/2006",
            campaign_app_list: "/campaign/app/3001",
            campaign_app_detail: "/campaign/app/3002",
            campaign_app_state: "/campaign/app/3003",
            campaign_app_new: "/campaign/app/3004",
            campaign_app_edit: "/campaign/app/3005",
            campaign_app_delete: "/campaign/app/3006",
            campaign_app_category: "/campaign/util/2001",
            campaign_creative_list: "/campaign/creative/11001",
            campaign_creative_detail: "/campaign/creative/11002",
            campaign_creative_state: "/campaign/creative/11004",
            campaign_creative_edit: "/campaign/creative/11003",
            campaign_creative_delete: "/campaign/creative/11005",
            campaign_creative_camp: "/campaign/operate/7001",
            campaign_creative_place: "/campaign/operate/5006",
            campaign_dashboard_data: "/campaign/dashboard/12001",
            campaign_dashboard_line: "/campaign/dashboard/12002",
            campaign_dashboard_bar: "/campaign/dashboard/12003",
            campaign_dashboard_camp: "/campaign/dashboard/12004",
            campaign_dashboard_list: "/campaign/dashboard/12005",
            campaign_dashboard_brand: "/campaign/dashboard/12006",
            campaign_dashboard_pie: "/campaign/dashboard/12007",
            campaign_dashboard_unique: "/campaign/dashboard/12008",
            campaign_dashboard_channel1: "/campaign/util/2015",
            campaign_dashboard_channel2: "/campaign/util/2017",
            campaign_dashboard_uniqueCsv: "/campaign/dashboard/12009",
            campaign_dashboard_reportCsv: "/campaign/dashboard/12010",
            campaign_appInfo_list: "/campaign/appInfo/10001",
            campaign_appInfo_detail: "/campaign/appInfo/10002",
            campaign_appInfo_delete: "/campaign/appInfo/10005",
            campaign_appInfo_category: "/campaign/operate/7006",
            campaign_offer_list: "/campaign/offer/20001",
            campaign_offerOn_list: "/campaign/offer/20006",
            campaign_offer_detail: "/campaign/offer/20002",
            campaign_offer_edit: "/campaign/operate/7013",
            campaign_offer_delete: "/campaign/offer/20005",
            campaign_offer_label: "/campaign/offer/20007",
            campaign_offer_cpx: "/campaign/offer/20004",
            campaign_offer_adver: "/campaign/owner/30006",
            campaign_offer_country: "/campaign/operate/7008",
            campaign_offer_group: "/campaign/util/2008",
            campaign_offer_place: "/campaign/util/2009",
            campaign_operate_list: "/campaign/operate/7007",
            campaign_operate_allAslist: "/campaign/operate/7017",
            campaign_operate_singleAslist: "/campaign/operate/7018",
            campaign_operate_netlist: "/campaign/operate/7019",
            campaign_operate_detail: "/campaign/operate/7002",
            campaign_operate_state: "/campaign/operate/7003",
            campaign_operate_new: "/campaign/operate/7004",
            campaign_operate_edit: "/campaign/operate/7005",
            campaign_network_new: "/campaign/operate/7014",
            campaign_network_edit: "/campaign/operate/7015",
            campaign_operate_delete: "/campaign/operate/7016",
            campaign_operate_img: "/campaign/util/2010",
            campaign_operate_area: "/campaign/operate/7008",
            campaign_operate_device: "/campaign/operate/7009",
            campaign_operate_os: "/campaign/operate/7010",
            campaign_operate_language: "/campaign/operate/7011",
            campaign_operate_channel1: "/campaign/util/2015",
            campaign_operate_channel2: "/campaign/util/2017",
            campaign_operate_channel3: "/campaign/util/2018",
            campaign_operate_apiVer: "/campaign/util/2019",
            campaign_operate_label: "/campaign/operate/7020",
            campaign_operate_adver: "/campaign/owner/30006",
            campaign_operate_offer: "/campaign/offer/20003",
            campaign_owner_list: "/campaign/owner/30001",
            campaign_owner_detail: "/campaign/owner/30002",
            campaign_owner_state: "/campaign/owner/30005",
            campaign_owner_new: "/campaign/owner/30004",
            campaign_owner_edit: "/campaign/owner/30003",
            campaign_owner_delete: "/campaign/owner/30007",
            campaign_report_csv: "/campaign/report/8005",
            campaign_report_chart: "/campaign/report/8006",
            campaign_report_list: "/campaign/report/8007",
            campaign_report_app: "/campaign/util/2013",
            campaign_report_placement: "/campaign/util/2020",
            campaign_report_camp: "/campaign/util/2014",
        }
    }
])
